[package]
name = "table"
version = "0.1.0"
authors = ["Naoto Kaneko <naoty.k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
csv = "1.1"
unicode-width = "0.1.7"
